using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace api.Dto.User
{
  public class NewUserDto
  {
    // Users identity number auto generated by the database 
    public string AppUserId { get; set; } = string.Empty;
    // Name of the user
    public string Name { get; set; } = string.Empty;
    // Surname of the user
    public string Surname { get; set; } = string.Empty;
    // Username of which the user prefers
    public string UserName { get; set; } = string.Empty;
    // Users email
    public string Email { get; set; } = string.Empty;
    // Date of which user registered
    public DateTime RegistrationDate { get; set; } = DateTime.Now;
    // Date of when user verified their email
    public DateTime VerifiedDate { get; set; }
    // Unique registration token of the user
    public string Token { get; set; } = string.Empty;
  }
}